// Code generated by protoc-gen-gorm_serializer. DO NOT EDIT.
// versions:
// - protoc             v3.15.8
// source: proto/lpt.proto

package proto

import "database/sql/driver"

func (x *Role) Scan(v any) (err error) {
	*x = Role(v.(int64))
	return nil
}

func (x Role) Value() (v driver.Value, err error) {
	return int64(x), nil
}
